### ISSUE TITLE
Add a section on "array vs iterator"

### ISSUE THREAD

**Issue by ljharb** [leobalter/object-keysin-valuesin-entries-in#1]
In anticipation of the question being asked, the doc should have a section like https://github.com/tc39/proposal-object-values-entries#iterators-or-arrays that pre-answers any objections folks who prefer one or the other might have.

**Comment by leobalter** [comment]
That section is very helpful. thanks!

**Comment by jdalton** [comment]
I see these additions (`keysIn`, `valuesIn`, etc.) as complementary to existing `keys`, `values`, etc. They're basically old method flavor + inherited string keyed properties.
