### ISSUE TITLE
Symbols?

### ISSUE THREAD

**Issue by ljharb** [leobalter/object-keysin-valuesin-entries-in#3]
`Reflect.enumerate` enumerated both Symbol and String keys. Currently, these methods enumerate only String keys.

The doc should have a section specifically addressing Symbols - why they are or are not included in the enumeration.

**Comment by leobalter** [comment]
sure. This proposal targets a similar approach from `for in` which skips Symbols. I'll prepare a section to address this.

**Comment by jdalton** [comment]
I don't think `Reflect.enumerate` did iterate Symbols. See [this](http://www.ecma-international.org/ecma-262/6.0/#sec-reflect.enumerate) then [this](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-enumerate):

> Return an Iterator object (25.1.1.2) whose next method iterates over all the String-valued keys of enumerable properties of O

**Comment by leobalter** [comment]
that's right. I remember I verified that when I wrote the api specs, but I forgot to check it again for this issue.

**Comment by ljharb** [comment]
aha, ok great clarification, thanks.

Given that, I think even a sentence would be more than sufficient to address Symbols.
