### ISSUE TITLE
The Foremost Question

### ISSUE THREAD

**Issue by gsklee** [leobalter/object-keysin-valuesin-entries-in#8]
Do we need this?

My opinion is "No" because it doesn't add or amend anything currently offered by the existing `for...in` statement. On the contrary, it will further clutter the `Object` namespace, leaving it with a range of confounding property extraction methods:

https://gist.github.com/gsklee/74674f86a688276c51e2333a10c7014c

Are we going to grow the list ever longer until we've exhausted all possible combinations out there?

**Comment by jdalton** [comment]
Naw, they're great! There's plenty of [use cases](https://github.com/leobalter/object-enumerables/issues/5), they're complementary, and they offer a compat path for modern first code. This API is proposed, in part, because spec folks decided to pull `Reflect.enumerate`.
